### PR TITLE
Add experimental alternate line document to allow replacement text

### PR DESCRIPTION
**Pull request by edmcman**

### CODE REVIEW

**Comment by edmcman** [comment]
This is not quite ready but is this close to what you were thinking?

**Comment by afranchuk** [comment]
Yeah, that's pretty much it! A few notes:

1. The `pp_line2` function leaks the allocation. Based on how `pp_free` works, you'd have to have some indicator about how the value was allocated, whether it be in the value, checking the pointer against the static ones (probably easiest), using a different doc type, or just always allocating one (not great since line breaks are common).
2. Since a non-space line break is common, that would probably be useful to have as a statically allocated thing with it's own convenience function to get it.

**Comment by edmcman** [comment]
Any idea for what to call `pp_line2` and `pp_line3`?

**Comment by afranchuk** [comment]
Maybe `pp_line` should be renamed `pp_space`, `pp_line2` (the one allowing arbitrary values) could be called `pp_breakable`, `pp_break`, or `pp_line` (not so sure about this one), and `pp_line3` (no separator) could be `pp_softbreak`?

**Comment by edmcman** [comment]
I like `pp_softbreak`.  It adds a break if needed, and otherwise adds nothing.  I think that will make sense to anyone who is familiar with a soft linebreak.  The only thing I don't like is that it mildly suggests that the other breaks are "hard", i.e., they _always_ add a break.

Here are some other rough ideas:

* pp_line, pp_line2, pp_line3
* `pp_break_or_space`, `pp_break_or`, `pp_softbreak`: Verbose but I think it's pretty clear, and there is consistency around "break".  `pp_break_or_space` is really long though, and it's the most common.
* `pp_sep` or `pp_space`, `pp_sep_by`, `pp_softbreak`: I like sep as an abbreviation for separate because it makes it clear that you are separating two documents, either with a line break or something else.

**Comment by afranchuk** [comment]
I like `pp_sep`, `pp_sep_by`, and `pp_softbreak`. I would like to keep a `pp_space` for warm-fuzzies (or to maybe make it a little more obvious that you generally shouldn't have spaces in `pp_string`s), though it could definitely just be a `#define`.

**Comment by edmcman** [comment]
Great, I'll rename those tomorrow, and add `pp_space`.

**Comment by edmcman** [comment]
Just noticed there is already a `pp_sep`.  I am trying to figure out what it does.

**Comment by edmcman** [comment]
https://github.com/afranchuk/prettyprint/blob/0a5b91b16084dd557eeda0652e0f3cf5416f8174/src/prettyprint_base.c#L91

I think this is adding a space if not present at the start of a new line.  Seems a bit redundant to me, as it can be accomplished with group and pp_line (old name).

**Comment by afranchuk** [comment]
Oh of course. I thought `sep` sounded too familiar... Your interpretation is almost right: it's simply a space, but it _won't_ add it if at the start or end of a line (because it's redundant and undesirable in those cases). But it's not the same as `pp_string(" ")` because that will require the space be added, and not the same as grouping `pp_line` because that will change to newlines (though actually in practice they'd end up being very similar if they are separating strings due to string wrapping).

So I think it's subtly different, but in practice it may not be that useful.

**Comment by edmcman** [comment]
So how should we proceed?  It is your library so your API :-)

I'm still a bit confused as to the utility of `sep`.  Maybe it is useful for dealing with the automatic line breaks from `pp_string`?

**Comment by afranchuk** [comment]
To put it another way, `sep` is a non-breaking space (won't be replaced by a newline) but the layout knows it should be ignored at the start or end of a line. It's actually kind of important now that I think about it, because it allows you to add whitespace between things but won't cause paragraphs to be expanded to linebreaks (relying on the `string` line breaking).

To show an example, consider a paragraph of text that would be represented in the following ways:
1. One big `pp_string`: this will wrap the text at the line width, but it's not aware of whitespace nor words, so you'll be breaking words and possibly introducing whitespace at the start of lines:
    ```
    pp_string("Rerum eveniet dolorem ducimus. Autem sit explicabo dolorem. Dolorem veniam velit maiores rem qui et laudantium deleniti.")
    ```
    would render as (30-character width)
    ```
    Rerum eveniet dolorem ducimus.
     Autem sit explicabo dolorem. 
    Dolorem veniam velit maiores r
    em qui et laudantium deleniti.
    ```

2. `pp_string` for each word separated by `pp_line`: this will render each word on a separate line since the group cannot all be rendered on one line (30-character width):
    ```
    Rerum
    eveniet
    dolorem
    ducimus.
    Autem
    sit
    explicabo
    dolorem.
    Dolorem
    veniam
    velit
    maiores
    rem
    qui
    et
    laudantium
    deleniti.
    ```

3. `pp_string` separated by `pp_sep`: this will add the spaces _if appropriate_, but omit them beside newlines. This also will properly move words to the next line if they don't fit, rather than breaking them arbitrarily (30-character width):
    ```
    Rerum eveniet dolorem ducimus.
    Autem sit explicabo dolorem. 
    Dolorem veniam velit maiores 
    rem qui et laudantium 
    deleniti.
    ```

So, this is actually an important distinction, most useful for paragraph layout. Obviously this isn't really approaching proper paragraph layout (with logical word-splits, etc.), but I'd say the behavior of (3) is far better than that of (1), and obviously (2) is not what was wanted.

Because of this, I think `pp_sep` should be renamed `pp_space` (deviating from the paper slightly, but that doesn't matter much), and then your new functions should be `pp_sep`, `pp_sep_by`, and `pp_softbreak`.

**Comment by edmcman** [comment]
Isn't this problem the same as `fillwords` in the paper?  They observe that `group (line)` will add a space if possible, and otherwise will add a line break.

I implemented this quickly here: https://github.com/edmcman/prettyprint/blob/fillwords/example/cpp-api.cpp#L22

I get the same result for a width of 30:
```
Rerum eveniet dolorem ducimus.
Autem sit explicabo dolorem. 
Dolorem veniam velit maiores 
rem qui et laudantium 
deleniti.
```

I think `pp_sep` (old name) is only needed to interact with line breaks that someone else is adding (e.g., `pp_words` / `pp_string`).  But the only place the user can interact with those functions is after, and I don't think either adds a trailing line break.  So if `pp_words` / `fillwords` can be implemented without `pp_sep` (old name), is there any need for it?

P.S. I am trying to be helpful and not difficult.  If I am being a pain let me know and I'll just rename things as you suggested above.

**Comment by afranchuk** [comment]
You're totally right, I somehow missed that entirely! In that case there should be no need for the existing `pp_sep` at all. Though it may be good to add a convenience function for `group(line)`; I see in other implementations _this_ is what's normally called `softbreak`.

You are being plenty helpful, don't worry!

**Comment by edmcman** [comment]
I have been super busy but I'll try to update the PR with the discussed changes soon

**Pull request merged**
